### PR TITLE
#157732935 A user can login (UI page)

### PR DESCRIPTION
**Pull request by dalaineme**
#### What does this PR do?
Showcases the simple UI design for user login.
#### Description of Task to be completed?
Simple page for user login by providing 
- Email Address
- Password
#### How should this be manually tested?

```sh
$ git clone https://github.com/dalaineme/m-tracker.git
```
```sh
$ cd m-tracker
```
> Open index.html
> Navigate to login page

#### Any background context you want to provide?
This is only the UI design. Page is not functional for now.
#### What are the relevant pivotal tracker stories?
#157732935
#### Screenshots (if appropriate)
login

#### Questions:
NA

### CODE REVIEW

**Comment by joelmachango** [comment]
@dcDalin Well structured PR. Nice design 👌

**Comment by zakhusayn** [comment]
The UI looks great. The PR detail description is quite shallow...Try to add some detail.

**Comment by PaulKitonyi** [comment]
Wow great UI @dalaineme.Please consider @blac-siren feedback and also make sure you merge into the right branch which is develop.

**Comment by maxwellgithinji** [comment]
@dalaineme , Super cool UI, however, there is so much going on that you haven't explained.

**Comment by artorious** [comment]
Looks Great, scales smoothly, Clean.

**Comment by mmosoroohh** [comment]
Love your design work....UI looks really awesome

**Pull request closed without merging**
